### ISSUE TITLE
Marina Package / Python

### ISSUE THREAD

**Issue by JessicaMatheron** [IlyaTrofimov/dlr#1]
Hi,

I'm reading your paper " Distributed Coordinate Descent for L1-regularized Logistic Regression" and I would like to test my intuition with the Python version of your code.

I'm having some trouble, which I can't seem to find help online for, with the line: 
from marina.base_metrics import get_metrics

The only marina package I can find online doesn't have a base_metrics module (see snapshot attached).
Could you please let me know how to proceed.

Thanks for making the code available btw, it is really appreciated!
Jessica

![marina](https://user-images.githubusercontent.com/34057195/34098537-0398931c-e3dd-11e7-95f9-6bd0e4deaa09.PNG)

**Comment by IlyaTrofimov** [comment]
Hi Jessica, 

Thank you for your interest.
First of all, I recommend you to read the more recent paper https://arxiv.org/abs/1611.02101
which describes a modified variant of the d-GLMNET algorithm.
And It is exactly what does the github code now.

The python code you mentioned is dedicated to running the program at the top of hadoop map/reduce cluster.
It is not a python interface (no c++ code binding), it is a wrapper for running ./dlr in the streaming mode.
The "marina" package is used for calculating performance measures like AUC, LogLoss, etc. and this dependency could be easily deleted.
The python code for cluster is somewhat dirty =) and no manual is available.
However, if you will tell me what you need - maybe I can help you.

If you want to use my code, maybe the ./fast_test.py is a good starting point.
This file contains simple tests with examples of command line arguments.
